"""At-risk learner classifier.

We train a RandomForest on synthetic engagement features whose ground-truth
label is generated by a noisy hidden rule. At inference time we surface, for
each prediction, the top-2 contributing features expressed in plain English -
this is what the instructor dashboard renders so the prediction is explainable.
"""

from __future__ import annotations

import logging
import threading
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

import joblib
import numpy as np

from ..config import BACKEND_ROOT

_log = logging.getLogger(__name__)
_lock = threading.Lock()
_model_cache = None

FEATURES = [
    "avg_quiz_score",
    "days_since_active",
    "completion_pct",
    "weekly_minutes",
    "mastery_avg",
    "help_requests",
    "confusion_incidents",
]

FEATURE_LABELS = {
    "avg_quiz_score": "low average quiz score",
    "days_since_active": "long gap since last activity",
    "completion_pct": "low course completion",
    "weekly_minutes": "low weekly time on platform",
    "mastery_avg": "mastery below cohort",
    "help_requests": "few help requests despite struggle",
    "confusion_incidents": "frequent confusion incidents",
}

POSITIVE_LABELS = {
    "avg_quiz_score": "strong quiz scores",
    "days_since_active": "recently active",
    "completion_pct": "good completion progress",
    "weekly_minutes": "healthy weekly engagement",
    "mastery_avg": "mastery above cohort",
    "help_requests": "actively seeking help",
    "confusion_incidents": "few confusion incidents",
}

_MODEL_PATH = BACKEND_ROOT / "data" / "at_risk_rf.joblib"


@dataclass
class RiskExplanation:
    feature: str
    label: str
    contribution: float


@dataclass
class RiskPrediction:
    risk_prob: float
    risk_band: str
    top_reasons: List[RiskExplanation]


def _hidden_ground_truth(row: np.ndarray) -> int:
    avg_quiz = row[0]
    days_inactive = row[1]
    completion = row[2]
    weekly_min = row[3]
    mastery = row[4]
    help_req = row[5]
    confusion = row[6]
    score = (
        -1.6 * avg_quiz
        + 0.06 * days_inactive
        - 1.2 * completion
        - 0.012 * weekly_min
        - 1.4 * mastery
        + 0.18 * confusion
        - 0.08 * help_req
        + 2.0
    )
    prob = 1.0 / (1.0 + np.exp(-score))
    return int(prob >= 0.5)


def _synthesize_cohort(n: int = 400, seed: int = 7) -> Tuple[np.ndarray, np.ndarray]:
    rng = np.random.default_rng(seed)
    X = np.column_stack(
        [
            rng.beta(5, 2, n),                              # avg_quiz_score
            rng.gamma(2.0, 2.0, n).clip(0, 30),             # days_since_active
            rng.beta(3, 2, n),                              # completion_pct
            rng.gamma(2.0, 60.0, n).clip(0, 600),           # weekly_minutes
            rng.beta(4, 3, n),                              # mastery_avg
            rng.poisson(1.5, n).astype(float),              # help_requests
            rng.poisson(1.0, n).astype(float),              # confusion_incidents
        ]
    )
    y = np.array([_hidden_ground_truth(row) for row in X], dtype=int)
    flip = rng.random(n) < 0.06
    y = np.where(flip, 1 - y, y)
    return X.astype(np.float32), y


def _train_model():
    from sklearn.ensemble import RandomForestClassifier

    X, y = _synthesize_cohort()
    clf = RandomForestClassifier(
        n_estimators=180,
        max_depth=6,
        min_samples_leaf=4,
        n_jobs=-1,
        random_state=42,
        class_weight="balanced",
    )
    clf.fit(X, y)
    cohort_mean = X.mean(axis=0)
    cohort_std = X.std(axis=0) + 1e-6
    return {
        "model": clf,
        "feature_names": list(FEATURES),
        "cohort_mean": cohort_mean.tolist(),
        "cohort_std": cohort_std.tolist(),
        "importances": clf.feature_importances_.tolist(),
    }


def _load_or_train():
    global _model_cache
    if _model_cache is not None:
        return _model_cache
    with _lock:
        if _model_cache is not None:
            return _model_cache
        if _MODEL_PATH.exists():
            try:
                _model_cache = joblib.load(_MODEL_PATH)
                _log.info("Loaded at-risk model from %s", _MODEL_PATH)
                return _model_cache
            except Exception as exc:  # noqa: BLE001
                _log.warning("Failed to load model, retraining: %s", exc)
        _log.info("Training at-risk RandomForest on synthetic cohort")
        _model_cache = _train_model()
        try:
            _MODEL_PATH.parent.mkdir(parents=True, exist_ok=True)
            joblib.dump(_model_cache, _MODEL_PATH)
        except Exception as exc:  # noqa: BLE001
            _log.warning("Could not persist model: %s", exc)
    return _model_cache


def warm_up() -> None:
    _load_or_train()


def predict(features: Dict[str, float]) -> RiskPrediction:
    bundle = _load_or_train()
    clf = bundle["model"]
    importances = np.asarray(bundle["importances"], dtype=np.float32)
    mean = np.asarray(bundle["cohort_mean"], dtype=np.float32)
    std = np.asarray(bundle["cohort_std"], dtype=np.float32)

    row = np.asarray([features.get(f, 0.0) for f in FEATURES], dtype=np.float32)
    risk_prob = float(clf.predict_proba(row.reshape(1, -1))[0, 1])

    z = (row - mean) / std
    direction = np.array([-1, +1, -1, -1, -1, -1, +1], dtype=np.float32)
    contributions = importances * z * direction
    order = np.argsort(-contributions)
    top_reasons: List[RiskExplanation] = []
    for idx in order[:2]:
        if contributions[idx] <= 0:
            continue
        feat = FEATURES[idx]
        top_reasons.append(
            RiskExplanation(
                feature=feat,
                label=FEATURE_LABELS[feat],
                contribution=float(contributions[idx]),
            )
        )
    if not top_reasons:
        idx = int(np.argmax(importances))
        feat = FEATURES[idx]
        top_reasons.append(
            RiskExplanation(
                feature=feat,
                label=POSITIVE_LABELS[feat],
                contribution=0.0,
            )
        )

    band = "high" if risk_prob >= 0.66 else "medium" if risk_prob >= 0.33 else "low"
    return RiskPrediction(risk_prob=risk_prob, risk_band=band, top_reasons=top_reasons)
