from __future__ import annotations

from .models import CourseModule, OnboardingRequest


COURSE_CATALOG: list[CourseModule] = [
    CourseModule(
        id="data-analytics-bootcamp",
        title="Data Analytics Bootcamp",
        program="atomcamp Data Analytics",
        level="beginner",
        duration_minutes=45,
        skills=["excel", "sql", "dashboards", "data storytelling", "business analytics"],
        outcomes=["build dashboards", "read datasets", "present insights"],
        best_for=["data analyst", "business analyst", "job switch", "fresh graduate"],
        project_seed="sales performance dashboard for a local business",
    ),
    CourseModule(
        id="ai-bootcamp",
        title="AI Bootcamp",
        program="atomcamp AI Bootcamp",
        level="beginner",
        duration_minutes=50,
        skills=["ai foundations", "prompting", "classification", "automation", "ethics"],
        outcomes=["prototype AI workflows", "explain model output", "ship AI demos"],
        best_for=["ai beginner", "student", "founder", "career growth"],
        project_seed="AI helper that summarizes customer feedback",
    ),
    CourseModule(
        id="agentic-ai",
        title="Make Your AI Agent",
        program="atomcamp Agentic AI",
        level="intermediate",
        duration_minutes=55,
        skills=["agents", "rag", "tool use", "workflow design", "evaluation"],
        outcomes=["design AI agents", "connect tools", "evaluate responses"],
        best_for=["automation", "developer", "founder", "productivity"],
        project_seed="AI agent for a small service business",
    ),
    CourseModule(
        id="automation-with-ai",
        title="Automation with AI",
        program="atomcamp Automation",
        level="intermediate",
        duration_minutes=40,
        skills=["workflow automation", "spreadsheets", "prompting", "apis", "no-code"],
        outcomes=["automate repetitive tasks", "connect apps", "save team time"],
        best_for=["busy professional", "operations", "entrepreneur", "office work"],
        project_seed="automated invoice and email follow-up workflow",
    ),
    CourseModule(
        id="python-camp",
        title="Python Camp",
        program="atomcamp Python",
        level="beginner",
        duration_minutes=35,
        skills=["python", "logic", "functions", "data handling", "debugging"],
        outcomes=["write scripts", "clean small datasets", "build foundations"],
        best_for=["beginner", "student", "career switch", "coding foundations"],
        project_seed="Python script that cleans enrollment data",
    ),
    CourseModule(
        id="ai-for-teens",
        title="AI for Teens",
        program="atomcamp Young Learners",
        level="beginner",
        duration_minutes=30,
        skills=["ai literacy", "creative prompts", "safe ai", "projects", "presentation"],
        outcomes=["understand AI basics", "make creative AI projects", "present ideas"],
        best_for=["teen", "school student", "creative learner", "beginner"],
        project_seed="AI-powered study buddy for school planning",
    ),
]


DEMO_LEARNERS: list[OnboardingRequest] = [
    OnboardingRequest(
        name="Ayesha",
        goal="Get a junior data analyst job in Karachi",
        background="Fresh BBA graduate with strong Excel basics and weak SQL",
        weekly_hours=7,
        language="Mixed",
        confidence=3,
        baseline_quiz=58,
        attendance_rate=84,
        activity_rate=66,
        motivation_style="job readiness",
        barriers=["needs interview portfolio", "gets stuck on SQL joins"],
        weak_skills=["sql", "data storytelling"],
    ),
    OnboardingRequest(
        name="Bilal",
        goal="Automate daily office reporting with AI agents",
        background="Busy operations manager with no coding background",
        weekly_hours=4,
        language="Urdu",
        confidence=2,
        baseline_quiz=46,
        attendance_rate=72,
        activity_rate=48,
        motivation_style="saving time at work",
        barriers=["limited study time", "low coding confidence"],
        weak_skills=["prompting", "workflow automation", "apis"],
    ),
    OnboardingRequest(
        name="Hina",
        goal="Build AI projects for university portfolio",
        background="CS student comfortable with Python but new to RAG",
        weekly_hours=10,
        language="English",
        confidence=4,
        baseline_quiz=76,
        attendance_rate=94,
        activity_rate=88,
        motivation_style="portfolio progress",
        barriers=["wants harder projects"],
        weak_skills=["rag", "evaluation"],
    ),
    OnboardingRequest(
        name="Omar",
        goal="Learn Python foundations before applying to bootcamps",
        background="First-year engineering student, beginner programmer",
        weekly_hours=6,
        language="Mixed",
        confidence=2,
        baseline_quiz=39,
        attendance_rate=68,
        activity_rate=52,
        motivation_style="small wins",
        barriers=["debugging anxiety", "missed last assignment"],
        weak_skills=["python", "logic"],
    ),
]

